
CREATE TABLE [tblSales](
	[nSaleID] [bigint] IDENTITY(1,1) NOT NULL,
	[sDesc] [varchar](255) NULL,
	[dCost] [money] NULL,
 CONSTRAINT [PK_tblSales] PRIMARY KEY CLUSTERED 
(
	[nSaleID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


